name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm
        run: npm ci
      - name: gulp
        run: gulp

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#deploy') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm
        run: npm ci
      - name: gulp
        run: gulp
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build

  new-version:
    needs: [test-and-build, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push a tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch