name: Deploy
on:
  push:
    branches:
      - master
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install npm
        run: npm ci
      - name: gulp
        run: gulp
      - name: download-webdrivers
        run: |
          mkdir ~/.webdrivers
          cd ~/.webdrivers
          wget http://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
          tar -xzf geckodriver-v0.29.0-linux64.tar.gz
          cd
          echo "export PATH=$PATH:~/.webdrivers" >> .bash_profile
      - name: e2e-tests
        run: gulp test:e2e
      - uses: actions/cache@v2
        id: npm-build-webdrivers-cache
        with:
          path: |
            build
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message), '#deploy') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: npm-build-webdrivers-cache
        with:
          path: |
            build
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build

  new-version:
    needs: [test-and-build, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push a tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch